### ISSUE TITLE
Downloaded S2 image is clipped

### ISSUE THREAD

**Issue by vascobnunes** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#19]
![fels-bug1](https://cloud.githubusercontent.com/assets/586591/22120025/bf218404-de75-11e6-9848-37e0e16af140.png)

command was the following:

C:\Users\vbnunes\Documents\GitHub\fetchLandsatSentinelFromGoogleCloud>python fetchFromGoogleCloud.py 29TNE S2 2016-02-01 2016-05-31 -c 10 -o c:\Temp --latest --outputcatalogs C:\Temp

**Comment by vascobnunes** [comment]
@bendv do you have any idea of how to programmatically distinguish a clipped tile from a full one?

**Comment by vascobnunes** [comment]
Discussing this here: http://gis.stackexchange.com/questions/227905/how-to-programmatically-distinguish-a-sentinel2-partial-and-full-tile/227908#227908

**Comment by bendv** [comment]
@vascobnunes thanks for the mention - I haven't had time to look at this recently, but I'll check this out once I get back to my S2 work

**Comment by vascobnunes** [comment]
@bendv I solved the issue with a not very elegant solution: the program downloads the images and then uses gdal to check if there are pixels with key=0; when existing - the image is clipped - and is deleted. (see check_full_tile()).
