### ISSUE TITLE
Downloaded images can not be displayed?

### ISSUE THREAD

**Issue by uahsan3** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#22]
Hi, I am new to GIS and thought you have a neat tool to download 2016's SENTINEL2 imagery. However, there are a lot of obscure folders in my download directory, and one folder I found "IMG_DATA" has images with extension ".jp2" and can not be opened with any software. 

Please advise. I want image tiles in RGB format for the year 2016 with 25% or less cloud cover. 

Thank you.

**Comment by vascobnunes** [comment]
Hello there!

Thank you for your question. Nice to see other people using this tool :)
If you open the XML file in the image root folder with qgis, it will build a virtual RGB.

Hope this is what you wanted.

**Comment by vascobnunes** [comment]
@uahsan3 do you still have this issue? can you make a capture screen video of what happens?

**Comment by vascobnunes** [comment]
or maybe you can ask in the GEE group: https://groups.google.com/forum/?fromgroups#!newtopic/google-earth-engine-developers
