### ISSUE TITLE
Selection of especifics bands of OLI_TIRS

### ISSUE THREAD

**Issue by Isaquedanielre** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#28]
Hi, I have been trying to get 3 bands of OLI, but I did not found the argument to especify the bands, something like this "-arg [B4.TIF, B5.TIF, B6.TIF]". 

There are or I need to develop?
Best
Isaque

**Comment by vascobnunes** [comment]
Hi Isaque. 
Thank you for your question and for using this script!
The idea to download all Landsat bands, however I just did a list of the ones that I could need at some point - which I think cover most cases. Please see https://github.com/vascobnunes/fetchLandsatSentinelFromGoogleCloud/blob/master/fetchFromGoogleCloud.py#L122-L123
So, If you need to get only 3 bands you may change this line or you may add some argument to control this. 
Please let me know if you further improve the script.
Regards
