### ISSUE TITLE
Runtime errors in both Python 2 and 3

### ISSUE THREAD

**Issue by GreatEmerald** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#29]
When trying to run the script using Python 3.6 (in a conda environment), I get the error  message:
```
  File "fetchFromGoogleCloud.py", line 129
    print "%2d%%" % percent,
                ^
SyntaxError: Missing parentheses in call to 'print'
```
This seems to be a typical problem of code not ported to Python 3, even though the readme says it should be compatible.

Meanwhile, attempting to run it from Python 2.7 results in a different error message:
```
Traceback (most recent call last):
  File "fetchFromGoogleCloud.py", line 17, in <module>
    apt install python-gdal""")
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```
This message goes away when GDAL is installed (`conda install gdal`), which indicates that this is an issue with the exception definition itself.

**Comment by vascobnunes** [comment]
Thank you for your comments. I'll try to find time to correct these.

**Comment by vascobnunes** [comment]
@GreatEmerald can you please verify if the python3 issue is solved in this new commit?

**Comment by GreatEmerald** [comment]
Not completely, now it's:
```
  File "fetchFromGoogleCloud.py", line 133
    print "Done."
                ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by vascobnunes** [comment]
yeah, missed that one. I think i got them all now

**Comment by vascobnunes** [comment]
Not sure how to fix the Python 2.7 error message though. My idea was to create the pip package and install the gdal dependency with it.

**Comment by GreatEmerald** [comment]
Yes, now in Python 3 I get the error:
```
Traceback (most recent call last):
  File "fetchFromGoogleCloud.py", line 13, in <module>
    from osgeo import gdal
ModuleNotFoundError: No module named 'osgeo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fetchFromGoogleCloud.py", line 17, in <module>
    apt install python-gdal""")
TypeError: exceptions must derive from BaseException
```
...which appears to be the Python 3 equivalent of the Python 2.7 error in the OP. Basically it's saying that a string is not a valid exception on its own, you need to create a `BaseException`-derived object for it to be handled properly.

As for the GDAL dependency, well, it is possible to use `pip` to install it, it is listed in `pip search` (as `GDAL`). But indeed there may also be an option to use the distribution package, or install it via `conda` (which generally does a better job at it than `pip`, GDAL is a pretty large dependency).

**Comment by GreatEmerald** [comment]
For reference, when I install GDAL into the Python 3 environment, `--help` works correctly; however, I get an error when running `-l` on Sentinel 2 data:
```
$ python fetchFromGoogleCloud.py 21NUE S2 2015-01-01 2017-07-20 -l
Downloading Metadata file...
Some error occurred when trying to download the Metadata file!
Unzipping Metadata file...
gzip: /tmp/index_Sentinel.csv.gz: No such file or directory
Searching for Sentinel-2 images in catalog...
Traceback (most recent call last):
  File "fetchFromGoogleCloud.py", line 303, in <module>
    main()
  File "fetchFromGoogleCloud.py", line 276, in main
    url = findS2InCollectionMetadata(sentinel2_metadata_file, options.cloudcover, options.start_date, options.end_date, options.scene, options.latest)
  File "fetchFromGoogleCloud.py", line 92, in findS2InCollectionMetadata
    with open(collection_file) as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/index_Sentinel.csv'
```
Unfortunately, it's not very clear what this "some error" during downloading is...

**Comment by GreatEmerald** [comment]
Trying this from a python shell, looks like the problem is that `urllib` in Python 3 does not have a function `urlretrieve`:
```python
>>> import urllib
>>> urllib.urlretrieve("http://storage.googleapis.com/gcp-public-data-sentinel-2/index.csv.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

In general it might be worth looking into different downloader packages. From what I've seen so far, even when it works, `urllib` is rather slow compared to `wget`, for instance. Other packages may also have nice features such as displaying the download speed, time until the download is completed, etc.

**Comment by vascobnunes** [comment]
That one comes from https://github.com/vascobnunes/fetchLandsatSentinelFromGoogleCloud/blob/master/fetchFromGoogleCloud.py#L31. Some problem occurred while trying urlretrieve

**Comment by GreatEmerald** [comment]
See the note at the top of this page for what changed in Python 3: https://docs.python.org/2.7/library/urllib.html
Looks like `urllib` has been removed and replaced with the former `urllib2` in Python 3. Making the syntax compatible with both versions may be tricky in that case.

**Comment by vascobnunes** [comment]
Yeah, I think this p2/p3 compatibility need more time to solve. I'll warn i the README
