### ISSUE TITLE
pip install: missing fetchFromGoogleCloud.py

### ISSUE THREAD

**Issue by GreatEmerald** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#30]
Unless I am missing something, using `pip install fels` as suggested in the readme does not actually fetch the script, only the metadata. `site-packages` directory contains only `FeLS-1.2.9.dist-info` directory, but not the script itself (and `find ~ -iname fetchFromGoogleCloud.py` returns nothing at all).

I tried this in both Python 2 and 3 in a conda environment (pip 9.0.1).

**Comment by vascobnunes** [comment]
Very rookie with creating pip packages. I need to find some time to look into this one. Sorry.

**Comment by GreatEmerald** [comment]
And thinking about it, it will probably not work as in the readme to just run `python fetchFromGoogleCloud.py`, because that implies that the script is in the working directory, which is not controlled by the package. I think the usual way to do that is to make the script executable (define a shebang) and place it somewhere in the `$PATH`. But I'm not very familiar with where pip may or may not write into either.
