### ISSUE TITLE
Default output directory

### ISSUE THREAD

**Issue by GreatEmerald** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#31]
At the moment, the output directory defaults to `/tmp`, which is almost always an undesirable location to store the downloaded data, since that is not a discoverable location, and the data is large whereas temporary file directories are limited in size (and often times the files put there are actually stored in memory by `tmpfs`).

A much more sensible default is to output the files in the working directory.

On a related note, it would be nice if the `--outputcatalogs` switch referred to a CSV file rather than a directory. The user may already have downloaded and extracted the catalog file somewhere, so passing the filename directly would save the trouble of redownloading and reextracting the file.

**Comment by vascobnunes** [comment]
Default output issue is solved. The --outputcatalogs doesn't download if file already in the stated dir.
