### ISSUE TITLE
Progress indicator takes up the entire console

### ISSUE THREAD

**Issue by GreatEmerald** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#35]
Testing with Python 2 now, and the progress indicator still has the issue where it outputs the percentage on its own line, followed by a blank line, thus erasing all the history of the console due to the sheer number of new lines it creates.

Ideally a download library should be used that already includes a progress bar out of the box, though.

**Comment by vascobnunes** [comment]
This was solved with https://github.com/vascobnunes/fetchLandsatSentinelFromGoogleCloud/pull/39
