### ISSUE TITLE
Sentinel 2: AUX_DATA is not downloaded

### ISSUE THREAD

**Issue by GreatEmerald** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#36]
I tried running `python fetchFromGoogleCloud.py 21NUE S2 2015-12-20 2017-12-24`, which downloads two SAFE directories, and when running `sen2cor` it told me that `AUX_DATA` directories inside `GRANULE` are missing. And that is indeed the case: there are only `IMG_DATA` and `QI_DATA` directories, whereas Google Cloud does also have the `AUX_DATA` directory:
https://console.cloud.google.com/storage/browser/gcp-public-data-sentinel-2/tiles/21/N/UE/S2A_MSIL1C_20151223T143139_N0201_R053_T21NUE_20151223T201036.SAFE/GRANULE/S2A_OPER_MSI_L1C_TL_SGS__20151223T165401_A002624_T21NUE_N02.01/
This directory holds a file with information on the ozone column, so it is important that it is downloaded as well. `sen2cor` doesn't run without it.

**Comment by vascobnunes** [comment]
The script should get all directories and files referenced in the manifest.safe file. I'll test on my side and get back to you

**Comment by GreatEmerald** [comment]
Well, that's the problem: AUX_DATA is not referenced in `manifest.safe` and yet it is required for `sen2cor`. In fact it doesn't look like it's referenced in any of the files. The script might just need to query Google about it.

**Comment by vascobnunes** [comment]
The way I deal with this is by creating this "AUX_DATA" dir, either manually or programatically. Does it work for you @GreatEmerald?

**Comment by GreatEmerald** [comment]
Yes, I did that as well, created those directories manually and put the files from Google Cloud on them.
