### ISSUE TITLE
Only get band 1

### ISSUE THREAD

**Issue by gh406** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#40]
Hi, I used the code to download landsat TM scenes but I only get band 1 per scene, do you have any solution? 

python fetchFromGoogleCloud.py 203031 OLI_TIRS 2015-01-01 2015-06-30 -c 30 -o F:\\DL\\OLI203031 --latest

in the folder I only found the metadata and LC82030312015170LGN00_B1.TIF

My python version is 2.7

Thanks in advance

**Comment by gh406** [comment]
I assume the problem locates at the line 114 target_file = os.path.join(target_path, img + "_" + band)

since here the blank makes the loop miss the rest of the bands

**Comment by vascobnunes** [comment]
Hi there. Thank you for your comments. I will look into it asap.
