### ISSUE TITLE
Missing files causing downloading error

### ISSUE THREAD

**Issue by jobobambam** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#46]
I followed the suggested install instructions for the fels package, but downloads are not occuring properly. Command line returns error for certain files and during the download the .SAFE folder appears, but then disappears upon command line task completion. A second run of the same line of code reveals the folder. I also tried the same install on mac and got the same error.
Any reason why my downloads are not working the first time?
Attached is screenshot of code errors
![image](https://user-images.githubusercontent.com/35681496/45085336-04fdf200-b133-11e8-9ab9-9c75c4df7aed.png)

**Comment by vascobnunes** [comment]
fixed in release 1.3.5 - also available in pypi
