### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by chexianghong** [vascobnunes/fetchLandsatSentinelFromGoogleCloud#48]
Hi, Vascobnunes

I use fetchLandsatSentinelFromGoogleCloud python code to download Sentinel data.  I used the test example in your readme file. The files were found, but something is wrong with downloading. The issue is as below:
![image](https://user-images.githubusercontent.com/33365292/47918103-87622280-dee6-11e8-8208-c6738ded5ebe.png)

I wonder if the error 404 would affect the Sentinel data.
Best,

**Comment by vascobnunes** [comment]
fixed in release 1.3.5 - also available in pypi
